### PR TITLE
fix(protoc-gen-grpc-gateway): error if identical annotations are provided

### LINKED ISSUE #1865: protoc-gen-grpc-gateway: Error if identical annotations are provided
## 📚 Documentation/Question

 Is there any detection mechanism to check for duplicates of the corresponding RESTful URIs when I generate the Grpc-gateway files?

### PR DESCRIPTION
**Pull request by danedavid**
#### References to other Issues or PRs
Fixes #1865 

#### Have you read the [Contributing Guidelines](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/CONTRIBUTING.md)?
Yes

#### Brief description of what is fixed or changed
Added a new map to `descriptor.Registry` to keep track of HTTP Verb-Template pairs, to check for duplicate annotations and error if found

### CODE REVIEW

File: internal/descriptor/registry.go [hunk 1]
```diff
@@ -115,13 +115,21 @@ type Registry struct {
 
 	// recursiveDepth sets the maximum depth of a field parameter
 	recursiveDepth int
+
+	// annotationMap is used to check for duplicate HTTP annotations
+	annotationMap map[annotationIdentifier]bool
```
Comment (johanbrandhorst) [inline internal/descriptor/registry.go:120]: Nit, but this could be slightly more efficient with an empty struct value:
```suggestion
	annotationMap map[annotationIdentifier]struct{}
```

File: protoc-gen-grpc-gateway/internal/gengateway/generator_test.go [hunk 2]
```diff
@@ -77,6 +77,7 @@ func newExampleFileDescriptorWithGoPkg(gp *descriptor.GoPackage, filenamePrefix
 
 func TestGenerator_Generate(t *testing.T) {
 	g := new(generator)
+	g.reg = descriptor.NewRegistry()
```
Comment (johanbrandhorst) [inline protoc-gen-grpc-gateway/internal/gengateway/generator_test.go:80]: Was this change necessary?

**Review by johanbrandhorst — CHANGES_REQUESTED** [review]
Thanks for this! Could you show me what the error looks like when it happens during generation too?

**Comment by danedavid** [comment]
@johanbrandhorst Here's how the error is shown in the terminal:

```
$ protoc -I . --grpc-gateway_out . \
    --grpc-gateway_opt logtostderr=true \
    --grpc-gateway_opt paths=source_relative \
    --grpc-gateway_opt generate_unbound_methods=true \
    samplepb/sample.proto

--grpc-gateway_out: duplicate annotation: method=GET, template=/v1/echo
```

File: protoc-gen-grpc-gateway/internal/gengateway/generator_test.go (hunk 2 above)
Comment (danedavid) [reply protoc-gen-grpc-gateway/internal/gengateway/generator_test.go:80]: Yes. `new(generator)` was not calling `NewRegistry` and without calling `NewRegistry` the map was not getting initialized, resulting in a panic. Let me know if there's a way to fix this without changing the test itself.

**Comment by danedavid** [comment]
Also I think this duplicate annotation from `a_bit_of_everything.proto` is causing `make generate` & `make test` to fail:

```proto
	rpc CheckExternalPathEnum(pathenum.MessageWithPathEnum) returns (google.protobuf.Empty) {
		option (google.api.http) = {
			get: "/v2/{value}:check"
		};
	}
	rpc CheckExternalNestedPathEnum(pathenum.MessageWithNestedPathEnum) returns (google.protobuf.Empty) {
		option (google.api.http) = {
			get: "/v2/{value}:check"
		};
	}
```

**Review by johanbrandhorst — COMMENTED** [review]
Thanks for the update, please feel free to remove examples which are broken and regenerate the files. I don't expect anyone actually wants to have this behavior.

**Review by johanbrandhorst — APPROVED** [review]
LGTM!

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!
