### PR TITLE
fix: Required field does not take effect

### LINKED ISSUE #2717: protoc_gen_openapiv2: Required field does not take effect under HTTP-GET
## 🐛 Bug Report

```
syntax = "proto3";
package test.v1;
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "api/test/v1;v1";
service TestsService {

    //  GetTest
    rpc GetTest (GetTestRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
        get: "/test"
        };
    }
}

// GetTestRequest
message GetTestRequest {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
        json_schema: {
            required: ["id"],
        }
    };
    // id.
    string id =1 ;
    // name.
    string name = 2;
}
```
## To Reproduce

```bash
protoc --proto_path=.  --openapiv2_out . --openapiv2_opt logtostderr=true test.proto 
```

## Expected behavior

in test.swagger.json  field id is required 

```json
        "parameters": [
          {
            "name": "id",
            "description": "id.",
            "in": "query",
            "required": true,
            "type": "string"
          }
```

## Actual Behavior
```json
        "parameters": [
          {
            "name": "id",
            "description": "id.",
            "in": "query",
            "required": false,
            "type": "string"
          }
```

### PR DESCRIPTION
**Pull request by MakDon**
Fix #2717

### CODE REVIEW

**Comment by MakDon** [comment]
The pipeline is complaining because the field `required` is switched from `false` to `true`
but i can not figure out why `x-optionalDataType: "String"` has been removed.

**Comment by johanbrandhorst** [comment]
Can you try just regenerating the files by following the instructions in CONTRIBUTING.md?

**Comment by MakDon** [comment]
I've regenerated the files.
But errors occurs when generating files, and it will stop the generating on Macos:
```[main] INFO io.swagger.codegen.AbstractGenerator - writing file /grpc-gateway/examples/internal/clients/abe/.swagger-codegen/VERSION
swagger-codegen generate -i examples/internal/proto/examplepb/a_bit_of_everything.swagger.json \
        -l go -o examples/internal/clients/abe --additional-properties packageName=abe
/usr/local/bin/swagger-codegen: 1: -e: not found
```
Following the error info, I found that there's a `-e` at the begginning of the file:
```
makdon-System-Product-Name% 
makdon-System-Product-Name% docker run -v $(pwd):/grpc-gateway -w /grpc-gateway --rm -it ghcr.io/grpc-ecosystem/grpc-gateway/build-env:1.17 "/bin/bash"
vscode ➜ /grpc-gateway (makdon-master) $ 
vscode ➜ /grpc-gateway (makdon-master) $ 
vscode ➜ /grpc-gateway (makdon-master) $ pwd
/grpc-gateway
vscode ➜ /grpc-gateway (makdon-master) $ which swagger-codegen 
/usr/local/bin/swagger-codegen
vscode ➜ /grpc-gateway (makdon-master) $ cat /usr/local/bin/swagger-codegen
-e #!/bin/bash
java -jar /usr/local/bin/swagger-codegen-cli.jar "$@"
vscode ➜ /grpc-gateway (makdon-master) $ swagger-codegen 
/usr/local/bin/swagger-codegen: line 1: -e: command not found
Available languages: [ada, ada-server, akka-scala, android, apache2, apex, aspnetcore, bash, csharp, clojure, cwiki, cpprest, csharp-dotnet2, dart, dart-jaguar, elixir, elm, eiffel, erlang-client, erlang-server, finch, flash, python-flask, go, go-server, groovy, haskell-http-client, haskell, jmeter, jaxrs-cxf-client, jaxrs-cxf, java, inflector, jaxrs-cxf-cdi, jaxrs-spec, jaxrs, msf4j, java-pkmst, java-play-framework, jaxrs-resteasy-eap, jaxrs-resteasy, javascript, javascript-closure-angular, java-vertx, kotlin, lua, lumen, nancyfx, nodejs-server, objc, perl, php, powershell, pistache-server, python, qt5cpp, r, rails5, restbed, ruby, rust, rust-server, scala, scala-gatling, scala-lagom-server, scalatra, scalaz, php-silex, sinatra, slim, spring, dynamic-html, html2, html, swagger, swagger-yaml, swift4, swift3, swift, php-symfony, tizen, typescript-aurelia, typescript-angular, typescript-inversify, typescript-angularjs, typescript-fetch, typescript-jquery, typescript-node, undertow, ze-ph, kotlin-server]
vscode ➜ /grpc-gateway (makdon-master) $
```
When I am using Macos, this error would stop the `make` and return an error. 
But when using Ubuntu, it reports the error and continues generating files.
What is this `-e` used for? Should we remove it to avoid it breaks the `make generate`?

**Comment by johanbrandhorst** [comment]
> I've regenerated the files. But errors occurs when generating files, and it will stop the generating on Macos:
> 
> ```
> swagger-codegen generate -i examples/internal/proto/examplepb/a_bit_of_everything.swagger.json \
>         -l go -o examples/internal/clients/abe --additional-properties packageName=abe
> /usr/local/bin/swagger-codegen: 1: -e: not found
> ```
> 
> Following the error info, I found that there's a `-e` at the begginning of the file:
> 
> ```
> makdon-System-Product-Name% 
> makdon-System-Product-Name% docker run -v $(pwd):/grpc-gateway -w /grpc-gateway --rm -it ghcr.io/grpc-ecosystem/grpc-gateway/build-env:1.17 "/bin/bash"
> vscode ➜ /grpc-gateway (makdon-master) $ 
> vscode ➜ /grpc-gateway (makdon-master) $ 
> vscode ➜ /grpc-gateway (makdon-master) $ pwd
> /grpc-gateway
> vscode ➜ /grpc-gateway (makdon-master) $ which swagger-codegen 
> /usr/local/bin/swagger-codegen
> vscode ➜ /grpc-gateway (makdon-master) $ cat /usr/local/bin/swagger-codegen
> -e #!/bin/bash
> java -jar /usr/local/bin/swagger-codegen-cli.jar "$@"
> vscode ➜ /grpc-gateway (makdon-master) $ swagger-codegen 
> /usr/local/bin/swagger-codegen: line 1: -e: command not found
> Available languages: [ada, ada-server, akka-scala, android, apache2, apex, aspnetcore, bash, csharp, clojure, cwiki, cpprest, csharp-dotnet2, dart, dart-jaguar, elixir, elm, eiffel, erlang-client, erlang-server, finch, flash, python-flask, go, go-server, groovy, haskell-http-client, haskell, jmeter, jaxrs-cxf-client, jaxrs-cxf, java, inflector, jaxrs-cxf-cdi, jaxrs-spec, jaxrs, msf4j, java-pkmst, java-play-framework, jaxrs-resteasy-eap, jaxrs-resteasy, javascript, javascript-closure-angular, java-vertx, kotlin, lua, lumen, nancyfx, nodejs-server, objc, perl, php, powershell, pistache-server, python, qt5cpp, r, rails5, restbed, ruby, rust, rust-server, scala, scala-gatling, scala-lagom-server, scalatra, scalaz, php-silex, sinatra, slim, spring, dynamic-html, html2, html, swagger, swagger-yaml, swift4, swift3, swift, php-symfony, tizen, typescript-aurelia, typescript-angular, typescript-inversify, typescript-angularjs, typescript-fetch, typescript-jquery, typescript-node, undertow, ze-ph, kotlin-server]
> vscode ➜ /grpc-gateway (makdon-master) $
> ```
> 
> When I am using Macos, this error would stop the `make` and return an error. But when using Ubuntu, it reports the error and continues generating files. What is this `-e` used for? Should we remove it to avoid it breaks the `make generate`?

I've seen this error a lot as well, and I've ignored it because it hasn't caused any issues. If it's causing a problem on MacOS we should definitely fix it, but would you mind making a separate PR? Thanks!

**Comment by MakDon** [comment]
Of course. I will make another PR for this after a second confirm.
But I can not find out where the dockerfile for `ghcr.io/grpc-ecosystem/grpc-gateway/build-env:1.17` locates.
And I do not have the permission to update the image on GitHub Packages

**Comment by MakDon** [comment]
After generating the files, more test breaks because the required field is added into the stubs.
I will work on it these days.

**Comment by johanbrandhorst** [comment]
I think it's this file: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/.github/Dockerfile. I've been pushing it manually (which is why the tag hasn't been updated for 1.18 yet 😬). Would be great if we had a Github actions job for it now that we've migrated away from CircleCI, but don't consider that a requirement - I can do a manual push once we have a PR. Thanks for your work on this!

File: examples/internal/clients/abe/api_a_bit_of_everything_service.go [hunk 1]
```diff
@@ -1559,7 +1531,7 @@ type ABitOfEverythingServiceCreateOpts struct {
...
+func (a *ABitOfEverythingServiceApiService) ABitOfEverythingServiceCreate(ctx context.Context, floatValue float32, doubleValue float64, int64Value string, uint64Value string, int32Value int32, fixed64Value string, fixed32Value int64, boolValue bool, stringValue string, uint32Value int64, sfixed32Value int32, sfixed64Value string, sint32Value int32, sint64Value string, nonConventionalNameValue string, enumValue string, pathEnumValue string, nestedPathEnumValue string, enumValueAnnotation string, uuid string, requiredStringViaFieldBehaviorAnnotation string, localVarOptionals *ABitOfEverythingServiceCreateOpts) (ExamplepbABitOfEverything, *http.Response, error) {
```
[the remark this answers is not in the document]
Comment (MakDon) [reply examples/internal/clients/abe/api_a_bit_of_everything_service.go:1534]: I have some ideas but I am not sure which is the best:
1. remove the `uuid` in required field
2. support `uuid` generated from client side ( And we should also update the test case)
3. fork `ABitOfEverything` as `CreateRequest`, in which `uuid` is not required.

[the remark this answers is not in the document]
Comment (johanbrandhorst) [reply examples/internal/clients/abe/api_a_bit_of_everything_service.go:1534]: I'm really confused. Can't we just fix the test? The server handler is not generated, we can just update it? Lets generate the UUID in the client?

[the remark this answers is not in the document]
Comment (MakDon) [reply examples/internal/clients/abe/api_a_bit_of_everything_service.go:1534]: Okay! I will just update the test cases later.

**Comment by MakDon** [comment]
The pipeline is complaining because it generates the files using codes from this PR, but compare it with the origin repo.
It can not be fixed by regenerate the files and commit into my branch.
Maybe we can just ignore it.

**Review by johanbrandhorst — CHANGES_REQUESTED** [review]

**Comment by johanbrandhorst** [comment]
> The pipeline is complaining because it generates the files using codes from this PR, but compare it with the origin repo. It can not be fixed by regenerate the files and commit into my branch. Maybe we can just ignore it.

Do you mind creating a separate PR that switches us to use the 1.19 container version for our generate job? Just edit [this](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/.github/workflows/ci.yml#L44) and [this](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/.github/workflows/ci.yml#L59).

**Comment by johanbrandhorst** [comment]
I'm confused as to why the CI generation would complain, it shouldn't compare against `main`, it should compare against this PR's contents. Looks to me like we just need to rerun generation again?

**Comment by MakDon** [comment]
> I'm confused as to why the CI generation would complain, it shouldn't compare against `main`, it should compare against this PR's contents. Looks to me like we just need to rerun generation again?

You're right. Sorry for my mistake.
I am trying to figure out the reason because I've tried to regenerate the files in [this commit](https://github.com/MakDon/grpc-gateway/commit/b99b7002fd030df28b9ffafbe99b8daf325c1c3e)

**Comment by johanbrandhorst** [comment]
I tried generating this locally as well and can't reproduce the diff, I'm very confused. Any chance you could rebase this on `main` and pull in the new `1.19` tag in the CI job?

**Comment by MakDon** [comment]
I closed this PR accidentally...
I've rebased and force pushed, and going to reopen and run the pipelines.

**Comment by MakDon** [comment]
The golangci is broken, I tried to reproduce it, and got the following message(which is not caused by this PR):
```
➜  grpc-gateway git:(makdon-master) golangci-lint version                                           
golangci-lint has version 1.48.0 built from 2d8fea81 on 2022-08-04T18:44:38Z
➜  grpc-gateway git:(makdon-master) golangci-lint run --enable goimports 
protoc-gen-grpc-gateway/main.go:6: File is not `goimports`-ed (goimports)
//   protoc --grpc-gateway_out=output_directory path/to/input.proto
protoc-gen-openapiv2/internal/genopenapi/generator.go:80: File is not `goimports`-ed (goimports)
//    JSON, we only want to add fields (see below, extensionMarshalJSON).
//    An infinite recursion would happen if we'd call json.Marshal on the struct
//    that has swaggerObject as an embedded field. To avoid that, we'll create
//    type aliases, and those don't have the custom MarshalJSON methods defined
//    on them. See http://choly.ca/post/go-json-marshalling/ (or, if it ever
//    goes away, use
//    https://web.archive.org/web/20190806073003/http://choly.ca/post/go-json-marshalling/.
protoc-gen-openapiv2/internal/genopenapi/template.go:32: File is not `goimports`-ed (goimports)
//  The OpenAPI specification does not allow for more than one endpoint with the same HTTP method and path.
//  This prevents multiple gRPC service methods from sharing the same stripped version of the path and method.
//  For example: `GET /v1/{name=organizations/*}/roles` and `GET /v1/{name=users/*}/roles` both get stripped to `GET /v1/{name}/roles`.
//  We must make the URL unique by adding a suffix and an incrementing index to each path parameter
//  to differentiate the endpoints.
//  Since path parameter names do not affect the request contents (i.e. they're replaced in the path)
//  this will be hidden from the real grpc gateway consumer.
protoc-gen-openapiv2/internal/genopenapi/template.go:7:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
        "io/ioutil"
        ^
utilities/readerfactory.go:6:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
        "io/ioutil"
        ^
internal/codegenerator/parse_req.go:6:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
        "io/ioutil"
        ^
```
So I ran `golangci-lint run --enable goimports --fix` that produces [this commit](https://github.com/grpc-ecosystem/grpc-gateway/pull/2829/commits/0dd750b031475fd00e614a442f5b27cf5ba3a816)
But I wonder if we should make another separate PR to do the formatting, and then rebase on it.

File: examples/internal/integration/client_test.go [hunk 2]
```diff
@@ -2,13 +2,17 @@ package integration_test
 
 import (
 	"context"
+	"fmt"
+	"github.com/rogpeppe/fastuuid"
```
[the remark this answers is not in the document]
Comment (MakDon) [reply examples/internal/integration/client_test.go]: Done, thanks for your review

File: examples/internal/integration/client_test.go [hunk 3]
```diff
@@ -2,13 +2,18 @@ package integration_test
...
 import (
 	"context"
+	"fmt"
 	"testing"
 
+	"github.com/rogpeppe/fastuuid"
+
 	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe"
 	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/echo"
 	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/unannotatedecho"
```
Comment (johanbrandhorst) [inline examples/internal/integration/client_test.go:12]: Sorry, I meant to put these all in the same import group. We generally use 2 import groups
```suggestion
	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/abe"
	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/echo"
	"github.com/grpc-ecosystem/grpc-gateway/v2/examples/internal/clients/unannotatedecho"
	"github.com/rogpeppe/fastuuid"
```

File: protoc-gen-openapiv2/internal/genopenapi/generator.go [hunk 4]
```diff
@@ -77,13 +77,14 @@ func mergeTargetFile(targets []*wrapper, mergeFileName string) *wrapper {
...
-//    goes away, use
-//    https://web.archive.org/web/20190806073003/http://choly.ca/post/go-json-marshalling/.
+//
+//	JSON, we only want to add fields (see below, extensionMarshalJSON).
+//	An infinite recursion would happen if we'd call json.Marshal on the struct
+//	that has swaggerObject as an embedded field. To avoid that, we'll create
+//	type aliases, and those don't have the custom MarshalJSON methods defined
+//	on them. See http://choly.ca/post/go-json-marshalling/ (or, if it ever
+//	goes away, use
+//	https://web.archive.org/web/20190806073003/http://choly.ca/post/go-json-marshalling/.
```
Comment (johanbrandhorst) [inline protoc-gen-openapiv2/internal/genopenapi/generator.go:87]: Revert this to the previous state by removing the extra spaces after `//`.

```suggestion
// JSON, we only want to add fields (see below, extensionMarshalJSON).
// An infinite recursion would happen if we'd call json.Marshal on the struct
// that has swaggerObject as an embedded field. To avoid that, we'll create
// type aliases, and those don't have the custom MarshalJSON methods defined
// on them. See http://choly.ca/post/go-json-marshalling/ (or, if it ever
// goes away, use
// https://web.archive.org/web/20190806073003/http://choly.ca/post/go-json-marshalling/.
```

File: protoc-gen-openapiv2/internal/genopenapi/template.go [hunk 5]
```diff
@@ -214,10 +214,13 @@ func (c *cycleChecker) Branch() *cycleChecker {
 
 // nestedQueryParams converts a field to a list of OpenAPI query parameters recursively.
 // This function is a helper function for queryParams, that keeps track of cyclical message references
-//  through the use of
-//      touched map[string]int
+//
+//	through the use of
+//	    touched map[string]int
+//
```
Comment (johanbrandhorst) [inline protoc-gen-openapiv2/internal/genopenapi/template.go:220]:
```suggestion
// through the use of
//
//	touched map[string]int
//
```

File: protoc-gen-openapiv2/internal/genopenapi/template.go [hunk 6]
```diff
@@ -214,10 +214,13 @@ func (c *cycleChecker) Branch() *cycleChecker {
...
 // If a cycle is discovered, an error is returned, as cyclical data structures are dangerous
-//  in query parameters.
+//
+//	in query parameters.
```
Comment (johanbrandhorst) [inline protoc-gen-openapiv2/internal/genopenapi/template.go:223]:
```suggestion
// in query parameters.
```

File: protoc-gen-openapiv2/internal/genopenapi/template_test.go [hunk 7]
```diff
@@ -651,7 +651,8 @@ func TestMessageToQueryParameters(t *testing.T) {
 }
 
 // TestMessagetoQueryParametersNoRecursive, is a check that cyclical references between messages
-//  are not falsely detected given previous known edge-cases.
+//
+//	are not falsely detected given previous known edge-cases.
```
Comment (johanbrandhorst) [inline protoc-gen-openapiv2/internal/genopenapi/template_test.go:655]:
```suggestion
// are not falsely detected given previous known edge-cases.
```

File: protoc-gen-openapiv2/internal/genopenapi/template_test.go [hunk 8]
```diff
@@ -770,8 +771,9 @@ func TestMessageToQueryParametersNoRecursive(t *testing.T) {
 }
 
 // TestMessagetoQueryParametersRecursive, is a check that cyclical references between messages
-//  are handled gracefully. The goal is to insure that attempts to add messages with cyclical
-//  references to query-parameters returns an error message.
+//
+//	are handled gracefully. The goal is to insure that attempts to add messages with cyclical
+//	references to query-parameters returns an error message.
```
Comment (johanbrandhorst) [inline protoc-gen-openapiv2/internal/genopenapi/template_test.go:776]:
```suggestion
// are handled gracefully. The goal is to insure that attempts to add messages with cyclical
// references to query-parameters returns an error message.
```

**Review by johanbrandhorst — CHANGES_REQUESTED** [review]
I see there were some formatting changes from our upgrade to 1.19, sorry about that. I've left comments on the changes that were made accidentally.

Thanks for your patience, we're almost there!

**Review by johanbrandhorst — APPROVED** [review]
LGTM!

**Comment by johanbrandhorst** [comment]
Thanks for your contribution and for your patience!
