### PR TITLE
bugfix: disable IOReaderFactory for streaming requests

### LINKED ISSUE #894: Change in behavior of streaming request body (1.4.1 vs 1.8.1)
### Steps you follow to reproduce the error:

I was using grpc-gateway (1.4.1) with github.com/tmc/grpc-websocket-proxy for using websockets to do bidirectional streaming. I recently updated to 1.8.1 and noticed that my web client was not behaving as expected. Further analysis showed that:
- the websocket proxy was reading messages from the browser appropriately and forwarding them to grpc-gateway,
- my grpc server was not receiving any messages.

I also saw that [this issue](https://github.com/tmc/grpc-websocket-proxy/issues/14) has been reported on the websocket-proxy project. 

It seems that the communication between the websocket proxy and the grpc server is blocked by ioutil.ReadAll. If I used a modified websocket proxy code that closes the request body after a few messages, the grpc server receives all the messages.

### What did you expect to happen instead:
The grpc server should receive each message as the websocket sends it. 

### What's your theory on why it isn't working:

This does seem to be related to the ioutil.ReadAll on the request Body.

### PR DESCRIPTION
**Pull request by happyalu**
An IOReaderFactory was being used to wrap request body for client/bidi streaming
requests.  This was causing the requests to be fully buffered before being sent
to the grpc server, thereby breaking streaming.  This commit changes that to
directly use request body.

Fixes #894

### CODE REVIEW

File: protoc-gen-grpc-gateway/gengateway/template_test.go [hunk 1]
```diff
@@ -391,8 +391,8 @@ func TestApplyTemplateRequestWithClientStreaming(t *testing.T) {
 		if want := spec.sigWant; !strings.Contains(got, want) {
 			t.Errorf("applyTemplate(%#v) = %s; want to contain %s", file, got, want)
 		}
-		if want := `marshaler.NewDecoder(newReader()`; !strings.Contains(got, want) {
-			t.Errorf("applyTemplate(%#v) = %s; want to contain %s", file, got, want)
+		if want := `marshaler.NewDecoder(newReader()`; strings.Contains(got, want) {
+			t.Errorf("applyTemplate(%#v) = %s; should not contain %s", file, got, want)
```
Comment (johanbrandhorst) [inline protoc-gen-grpc-gateway/gengateway/template_test.go]: This test is a bit silly, so just remove this if case.

**Comment by johanbrandhorst** [comment]
Could you try building the grpc-gateway generator off this branch and see if it fixes https://github.com/tmc/grpc-websocket-proxy/issues/14 for you?

File: protoc-gen-grpc-gateway/gengateway/template_test.go (hunk 1 above)
Comment (happyalu) [reply protoc-gen-grpc-gateway/gengateway/template_test.go]: removed.

**Comment by happyalu** [comment]
> Could you try building the grpc-gateway generator off this branch and see if it fixes [tmc/grpc-websocket-proxy#14](https://github.com/tmc/grpc-websocket-proxy/issues/14) for you?

Yes, my websocket client is working again.

**Comment by johanbrandhorst** [comment]
Thank you so much for this contribution!
