### PR TITLE
[issue-6080] Fix strict `no-$ref-siblings` rule violations

### LINKED ISSUE #6080: protoc-gen-openapiv2 violation of strict rule `no-$ref-siblings`
## 🐛 Bug Report

When using protoc-gen-openapiv2, the generated open api v2 definition contains undesired:

```
{
  ...
  "items": {
    "type": "object",
    "$ref": "#/definitions/demoItemWithChoice"
  },
  ...
}
```

## To Reproduce

1. clone https://github.com/jgreffe/protoc-gen-openapiv2-siblings
2. follow readme.md

## Expected behavior
Generated definition should contain `$ref` without siblings:
```
{
  ...
  "items": {
    "$ref": "#/definitions/demoItemWithChoice"
  },
  ...
}
```

## Actual Behavior
```
{
  ...
  "items": {
    "type": "object",
    "$ref": "#/definitions/demoItemWithChoice"
  },
  ...
}
```

## Your Environment
N/A

### PR DESCRIPTION
**Pull request by jgreffe**
#### References to other Issues or PRs

Fixes #6080 

#### Brief description of what is fixed or changed

Introduce a new option `omit_array_item_type_when_ref_sibling` which allows to omit a `type: object` if a `$ref` already exists.
This fixes strict `no-$ref-siblings` rule violations.
But default this option is `false` to keep previous behavior.

### CODE REVIEW

File: protoc-gen-openapiv2/internal/genopenapi/template_test.go [hunk 1]
```diff
@@ -10498,6 +10498,247 @@ func TestArrayMessageItemsType(t *testing.T) {
 	}
 }
 
+func TestArrayMessageItemsTypeOmitWhenRefSibling(t *testing.T) {
```
Comment (jgreffe) [inline protoc-gen-openapiv2/internal/genopenapi/template_test.go]: almost the same test as [TestArrayMessageItemsType](https://github.com/jgreffe/grpc-gateway/blob/f8c135ede12a9540475d1d5459ff325a95dc3b3a/protoc-gen-openapiv2/internal/genopenapi/template_test.go#L10262), but we check we don't have results like [these](https://github.com/jgreffe/grpc-gateway/blob/f8c135ede12a9540475d1d5459ff325a95dc3b3a/protoc-gen-openapiv2/internal/genopenapi/template_test.go#L10414-L10415).

**Comment by johanbrandhorst** [comment]
Looks like a minor formatting issue in the bazel file, I would ignore the fuzz error

**Comment by johanbrandhorst** [comment]
Thanks for your contribution!
