### PR TITLE
ability to customize stream errors

### LINKED ISSUE #584: Errors in response streams do not go through the registered error handler
I am using `runtime.WithProtoErrorHandler` to provide custom error handling in my service. In particular, my service discards the error message (and provides a default based on the gRPC code) unless the error includes details that specify a "safe" message (e.g. no stack trace or other internal details leaked). I also have a slightly modified mapping of gRPC codes to HTTP codes.

But if I have a bidi- or server-streaming endpoint, the error will get converted into a `StreamError` message in a way that is not pluggable/configurable. That means the `err.Error()` or `stat.Message()` is rendered in the response chunk with no ability to customize it (such as stripping away any inappropriate details that are present in the message).

I understand that the existing `ProtoErrorHandlerFunc` type is not necessarily appropriate for use with a streaming response, since it assumes it can set a response code and response headers. So I think a new `ServerMuxOption` is necessary for this.

Proposal (two-pronged):

1. Use `ProtoErrorHandlerFunc` when possible -- e.g. when no response messages have actually been sent back.
2. Add new `ServerMuxOption` for rendering errors, maybe a signature like so:
`func(context.Context, error) *StreamError`

That second part could even be extended to customizing the envelope that is used for streaming response messages. Instead of a function, it could be an interface:

```
type StreamChunkHandler interface {
    HandleResponse(context.Context, proto.Message) interface{}
    HandleError(context.Context, error) interface{}
}
```
This allows for using a custom envelope as well as using a custom error representation, too. The returned item from these methods would then be passed to the configured `Marshaler` for rendering to the HTTP stream.

### PR DESCRIPTION
**Pull request by jhump**
Fixes #584

### CODE REVIEW

File: runtime/mux.go [hunk 1]
```diff
@@ -110,6 +111,20 @@ func WithDisablePathLengthFallback() ServeMuxOption {
 	}
 }
 
+// WithStreamErrorHandler returns a ServeMuxOption that will use the given custom stream
+// error handler, which allows for customizing the error trailer for server-streaming
+// calls.
+//
+// For stream errors that occur before any response has been written, the mux's
+// ProtoErrorHandler will be invoked. However, once data has been written, the errors must
+// be handled differently: they must included in the response body. The response body's
```
Comment (johanbrandhorst) [inline runtime/mux.go]:
```suggestion
// be handled differently: they must be included in the response body. The response body's
```

File: runtime/proto_errors.go [hunk 2]
```diff
@@ -8,8 +8,17 @@ import (
 	"google.golang.org/grpc/codes"
 	"google.golang.org/grpc/grpclog"
 	"google.golang.org/grpc/status"
+	"github.com/grpc-ecosystem/grpc-gateway/runtime/internal"
```
Comment (johanbrandhorst) [inline runtime/proto_errors.go]: Could you run `goimports` on this file please? I think this import should be above the grpc ones.

File: runtime/handler.go [hunk 3]
```diff
@@ -168,18 +168,30 @@ func handleForwardResponseOptions(ctx context.Context, w http.ResponseWriter, re
...
+
+	// otherwise, render the error as a stream chunk in the response
+	var chunk map[string]proto.Message
+	if mux.streamErrorHandler != nil {
+		serr := mux.streamErrorHandler(ctx, err)
+		if serr == nil {
+			// TODO: log error about misbehaving error handler?
+			chunk = streamChunk(nil, err)
+		} else {
+			chunk = map[string]proto.Message{"error": (*internal.StreamError)(serr)}
```
Comment (johanbrandhorst) [inline runtime/handler.go]: Not sure if this was discussed in #584, but this still doesn't give the user the power to fully control the envelope, right? Is that intentional?

File: runtime/handler.go [hunk 4]
```diff
@@ -168,18 +168,30 @@ func handleForwardResponseOptions(ctx context.Context, w http.ResponseWriter, re
...
 		}
-		w.WriteHeader(HTTPStatusFromCode(s.Code()))
+	} else {
+		chunk = streamChunk(nil, err)
+	}
```
Comment (johanbrandhorst) [inline runtime/handler.go]: Instead of this if-else, we could set the `mux.streamErrorHandler` to `streamChunk` by default (before iterating the options).

File: runtime/handler.go (hunk 3 above)
Comment (jhump) [reply runtime/handler.go]: I added a comment earlier to that issue about why I felt that was ultimately a bad idea: a custom envelope in the runtime would make it impossible for a protoc plugin to generate a correct swagger/OpenAPI spec for the service.

Comment (johanbrandhorst) [reply runtime/handler.go]: Fair enough

**Comment by jhump** [comment]
@johanbrandhorst, the build errors aren't making a lot of sense to me. I'm not a bazel user, but I understand the concepts (I've used blaze and pants). I tried to add a dependency from the runtime package to runtime/internal (surprised it was not already present), but that is still failing.

Any advice on getting the build green? I'm also really confused about the other errors, which appear to be related to Go modules. The confusing thing is that a few lines up from the error, it states that it resolved "github.com/grpc-ecosystem/grpc-gateway/runtime", but somehow can't resolve the "internal" sub-package therein :(

I can keep hacking, but if you can spot any simple issues in here, that would certainly speed things up.

**Comment by johanbrandhorst** [comment]
> @johanbrandhorst, the build errors aren't making a lot of sense to me. I'm not a bazel user, but I understand the concepts (I've used blaze and pants). I tried to add a dependency from the runtime package to runtime/internal (surprised it was not already present), but that is still failing.
> 
> Any advice on getting the build green? I'm also really confused about the other errors, which appear to be related to Go modules. The confusing thing is that a few lines up from the error, it states that it resolved "github.com/grpc-ecosystem/grpc-gateway/runtime", but somehow can't resolve the "internal" sub-package therein :(
> 
> I can keep hacking, but if you can spot any simple issues in here, that would certainly speed things up.

Something about this import certainly seems to have got Go modules confused - I also have no idea what the hell is wrong here. I'll do some more investigating.

File: runtime/BUILD.bazel [hunk 5]
```diff
@@ -30,6 +30,7 @@ go_library(
         "@com_github_golang_protobuf//jsonpb:go_default_library_gen",
         "@com_github_golang_protobuf//proto:go_default_library",
         "@com_github_golang_protobuf//protoc-gen-go/generator:go_default_library_gen",
+        "@com_github_grpc_ecosystem_grpc_gateway//runtime/internal:go_default_library",
```
Comment (johanbrandhorst) [inline runtime/BUILD.bazel]: I don't think this should be necessary, I can't imagine we don't already import the internal package somewhere in here and it's worked in the past.

**Comment by johanbrandhorst** [comment]
Wait, `runtime/internal` isn't a package. You must mean `github.com/grpc-ecosystem/grpc-gateway/internal`? The `internal` package moved. @jhump.

**Comment by jhump** [comment]
> Wait, runtime/internal isn't a package. You must mean github.com/grpc-ecosystem/grpc-gateway/internal? The internal package moved. @jhump.

Doh! Thanks for the tip. (You can probably tell that this patch was rebased from an older version of the repo. We've had it in a fork that is apparently pretty old: 463c5eda4ce58dd590b94bd2ac931db6790a1d2c, from March 2018.)

**Comment by johanbrandhorst** [comment]
> > Wait, runtime/internal isn't a package. You must mean github.com/grpc-ecosystem/grpc-gateway/internal? The internal package moved. @jhump.
> 
> Doh! Thanks for the tip. (You can probably tell that this patch was rebased from an older version of the repo. We've had it in a fork that is apparently pretty old: [463c5ed](https://github.com/grpc-ecosystem/grpc-gateway/commit/463c5eda4ce58dd590b94bd2ac931db6790a1d2c), from March 2018.)

I celebrate the implication that you're trying to go back to the source :). I hope we can make you feel at home!

File: runtime/handler.go (hunk 4 above)
Comment (johanbrandhorst) [reply runtime/handler.go]: Still relevant

File: runtime/proto_errors.go [hunk 6]
```diff
@@ -1,15 +1,24 @@
 package runtime
 
 import (
+	"context"
 	"io"
 	"net/http"
 
-	"context"
+        "github.com/grpc-ecosystem/grpc-gateway/internal"
```
Comment (johanbrandhorst) [inline runtime/proto_errors.go]: :eyes: spaces for indentation in a go file? :scream:

Comment (jhump) [reply runtime/proto_errors.go]: Not sure what happened there. Ran `gofmt` on it.

File: runtime/handler.go (hunk 4 above)
Comment (jhump) [reply runtime/handler.go]: Just pushed changes to address this. WDYT?

File: runtime/proto_errors.go [hunk 7]
```diff
@@ -1,15 +1,27 @@
...
 
+// StreamErrorHandlerFunc accepts an error as a gRPC error generated via status package and translates it into a
+// a proto struct used to represent error at the end of a stream.
+type StreamErrorHandlerFunc func(context.Context, error) *StreamError
+
+// StreamError is the payload for the final message in a server stream in the event that the server returns an
+// error after a response message has already been sent.
+type StreamError internal.StreamError
+
+var _ StreamErrorHandlerFunc = DefaultHTTPStreamErrorHandler
```
Comment (johanbrandhorst) [inline runtime/proto_errors.go]: This shouldn't be necessary, line 134 in mux.go guarantees this.

File: runtime/handler.go [hunk 8]
```diff
@@ -168,48 +168,41 @@ func handleForwardResponseOptions(ctx context.Context, w http.ResponseWriter, re
 	return nil
 }
 
-func handleForwardResponseStreamError(wroteHeader bool, marshaler Marshaler, w http.ResponseWriter, err error) {
-	buf, merr := marshaler.Marshal(streamChunk(nil, err))
+func handleForwardResponseStreamError(ctx context.Context, wroteHeader bool, marshaler Marshaler, w http.ResponseWriter, req *http.Request, mux *ServeMux, err error) {
+	if !wroteHeader {
+		// if we haven't already written header, use normal error handler to render
+		HTTPError(ctx, mux, marshaler, w, req, err)
+		return
```
Comment (johanbrandhorst) [inline runtime/handler.go]: Is this backwards compatibility breaking? I can see we used to do just `w.WriteHeader` here.

File: runtime/handler.go (hunk 4 above)
Comment (johanbrandhorst) [reply runtime/handler.go]: Much better :). Left a few more comments.

File: runtime/handler.go (hunk 8 above)
Comment (jhump) [reply runtime/handler.go]: I guess technically it is (though the behavior in this case isn't really specified, at least not that I can find).

Previously, it would emit a JSON response body like so:
```json
{
  "error": {
    "grpc_code": 13,
    "http_code": 500,
    "message": "some error occurred",
    "http_status": "Internal Server Error",
    "details": [],
  }
}
```

Now, it will emit a response body like this instead:

```json
{
  "code": 13,
  "message": "some error occurred",
  "details": [],
}
```

The actual HTTP status code sent back would be the same (in the example: "500 Internal Server Error").

IMO, this makes it cohesive and consistent: if the client gets a non-200 status code, the response format is the same (regardless of whether the method was a streaming or unary method). So it feels more like a fix and will also simplify the specification/documentation of error handling.

But if that is too great of a change, how about the following alternative logic:

1. Call `streamErrorChunk` to let custom handler produce custom stream error message.
2. Use the resulting error's `HttpCode` to set the response code (if `!wroteHeader`).

Comment (johanbrandhorst) [reply runtime/handler.go]: The swagger generator defines the error format for streams including the envelope, so I would prefer the consistency, even though I understand your point about the non-200 error code response.

Comment (jhump) [reply runtime/handler.go]: > The swagger generator defines the error format for streams including the envelope

Oh, it does? I guess that must be another fix that isn't in our old fork. (When I run the swagger protoc plugin in our repo, it emits the wrong definition.)

Okay, in that case, I'll tweak this behavior.

Comment (jhump) [reply runtime/handler.go]: > The swagger generator defines the error format for streams including the envelope

Out of curiosity, is this spec meant for interpreting responses for _successful_ calls only? Does swagger even allow specifying different response types based on error-vs-ok conditions? Because currently, unary RPCs may not be correctly encoded in swagger for non-200 response codes. (Maybe that's only in my old fork of the repo?)

Comment (johanbrandhorst) [reply runtime/handler.go]: It's an optional field in the response, so the swagger definition shows the "result" key and the "error" for all responses.

**Comment by jhump** [comment]
@johanbrandhorst: I think this is ready for another pass, whenever you get a chance.

File: runtime/handler.go [hunk 9]
```diff
@@ -168,48 +168,42 @@ func handleForwardResponseOptions(ctx context.Context, w http.ResponseWriter, re
...
+	if serr != nil {
+		return serr
+	}
+	// TODO: log about misbehaving stream error handler?
+	return DefaultHTTPStreamErrorHandler(ctx, err)
+}
+
+func errorChunk(err *StreamError) map[string]proto.Message {
+	return map[string]proto.Message{"error": (*internal.StreamError)(err)}
+}
```
Comment (johanbrandhorst) [inline runtime/handler.go]: This is an opinion so feel free to push back; I think it would be nicer to merge this function into streamError. I might be wrong but it seems to me the value from streamError is only used as a parameter to errorChunk and this separation is only making things unnecessarily complicated. Again, please feel free to push back.

Comment (jhump) [reply runtime/handler.go]: I originally had it that way. But above, I actually need the `*StreamError` to set the HTTP status code when no header has been written. So I either needed to break it up into two functions or have the function above try to dig it out of the chunk map and type-convert it (which seemed like the much grosser option).

**Comment by jhump** [comment]
> How do you feel about my suggestion to add some documentation about this new feature too?

I added a section to the "Customizing your Gateway" doc page. PTAL.
